# Generated by Django 4.2.17 on 2025-02-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nutritionapp', '0002_trackerdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerdata',
            name='nutrients',
        ),
    ]
